// BossPoolTable.h - GENERATED by tools/gen_pool_table.py boss.
// Do not edit by hand; regenerate and re-run the matching verifier.
//
// Every model that can appear in the BOSS randomizer's candidate pool,
// per docs/plans/boss-randomization.md section 4.2 - the boss-name list,
// minus the eligibility rejects, minus the narrower insert-reject list.
//
// Note this pool is DRAINED and refilled as bosses are assigned, so a
// selection of one model means every boss arena gets that model.
//
// ORDER IS LOAD-BEARING: RandomizerDefaults stores the picker's selection
// as one character per row, positionally. Sorted by display name, then by
// model id to break ties - see the generator's header comment.
//
// Names are from tools/data/Characters.json (Smithbox, MIT) and are the
// community's labels, not From Software's - treated the same way every
// other name in this project is: useful, not authoritative.
//
// `poolEntries` is how many distinct stat/AI variants that model
// contributes, i.e. its relative draw weight. Unused by the app today;
// baked because it is free here and docs/deferred-ideas.md §2 needs it.
#pragma once

#include <array>

#include "ModelPoolSelection.h"

namespace bbr {

// Kept as a function-local static for the same reason as
// EnemyExclusionList(): header-only, no translation-unit duplication.
inline const std::array<ModelPoolEntry, 17>& BossPoolTable() {
    static const std::array<ModelPoolEntry, 17> kTable = {{
        { "c5120", "AMYGDALA",                              1 },
        { "c2090", "BLOOD STARVED BEAST",                   1 },
        { "c5000", "CLERIC BEAST",                          1 },
        { "c5080", "DARKBEAST PAARL",                       1 },
        { "c2510", "EBRIETAS, DAUGHTER OF THE COSMOS",      1 },
        { "c2710", "FATHER GASCOINGE",                      1 },
        { "c2720", "FATHER GASCOINGE (BEAST)",              1 },
        { "c8050", "GEHRMAN (BOSS)",                        1 },
        { "c4520", "LADY MARIA OF THE ASTRAL CLOCKTOWER",   1 },
        { "c4500", "LAURENCE, THE FIRST VICAR",             1 },
        { "c4510", "LUDWIG, THE HOLY BLADE",                2 },
        { "c2320", "MATYR LOGARIUS",                        1 },
        { "c5510", "MERGO'S WET NURSE",                     1 },
        { "c5400", "MOON PRESENCE",                         1 },
        { "c5100", "ROM, THE VACUOUS SPIDER",               1 },
        { "c4541", "STANDING ORPHAN OF KOS (FLAPS)",        1 },
        { "c5020", "VICAR AMELIA",                          1 },
    }};
    return kTable;
}

const int kBossPoolModelCount = 17;

} // namespace bbr
