// EnemySkipTable.h - GENERATED by tools/gen_pool_table.py skip.
// Do not edit by hand; regenerate and re-run the matching verifier.
//
// Every model the ENEMY randomizer is allowed to OVERWRITE - the other
// side of the pool. A row ticked in ENEMIES SKIPPED leaves that creature
// out of the run in both directions: its own placements are never
// rewritten, and it never arrives as a replacement. See feature 032.
//
// This is NOT EnemyPoolTable.h with extra rows and must never be derived
// from it. The two answer different questions - what can be REPLACED
// versus what can REPLACE - and they carry different per-row numbers.
// The 82 pool models are a strict subset of these 85; the three extras
// are c1130, c2121 (both ThinkParamID <= 1, so neither can enter the
// pool) and c2561 (dropped by an explicit name test in the pool loop).
//
// `poolEntries` therefore counts PLACEMENTS PROTECTED, not draw weight:
// nothing draws from this table. The column sums to 2269.
//
// ORDER IS LOAD-BEARING: RandomizerDefaults stores the picker's selection
// as one character per row, positionally. Sorted by display name, then by
// model id to break ties - see the generator's header comment.
//
// Names are from tools/data/Characters.json (Smithbox, MIT) and are the
// community's labels, not From Software's - treated the same way every
// other name in this project is: useful, not authoritative.
#pragma once

#include <array>

#include "ModelPoolSelection.h"

namespace bbr {

// Kept as a function-local static for the same reason as
// EnemyExclusionList(): header-only, no translation-unit duplication.
inline const std::array<ModelPoolEntry, 85>& EnemySkipTable() {
    static const std::array<ModelPoolEntry, 85> kTable = {{
        { "c2180", "ABHORRENT BEAST",                    10 },
        { "c5040", "ABHORRENT BEAST",                     4 },
        { "c1091", "BEAST PATIENT",                       3 },
        { "c7500", "BEAST POSSESSED SOUL",                2 },
        { "c4100", "BLOOD DOBERMANN",                     6 },
        { "c2090", "BLOOD STARVED BEAST",                 1 },
        { "c2130", "BLOODLICKER",                         9 },
        { "c4130", "BLOODLICKER",                        12 },
        { "c1060", "BRAINSUCKER",                        19 },
        { "c2640", "BRICK TROLL",                        35 },
        { "c2561", "C2561",                               9 },
        { "c1220", "CAINHURST GARGOYLE",                 12 },
        { "c2330", "CAINHURST SERVANT",                  16 },
        { "c1170", "CARRION CROW",                      202 },
        { "c1171", "CARRION CROW (DOG FACE)",             9 },
        { "c2520", "CELESTIAL LARVAE",                   48 },
        { "c2521", "CELESTIAL LARVAE",                    3 },
        { "c2730", "CHAPEL GIANT",                       20 },
        { "c1050", "CHIME MAIDEN",                       31 },
        { "c1051", "CHIME MAIDEN (LIGHT)",               23 },
        { "c2700", "CHURCH SERVANT",                     34 },
        { "c1090", "CLOAKED BEAST PATIENT",             104 },
        { "c4140", "CLOAKED BEAST PATIENT",              29 },
        { "c1290", "CLOAKED BEAST PATIENT (FEMALE)",     19 },
        { "c3100", "CRAMPED CASKET",                     22 },
        { "c2550", "CRAWLER",                            20 },
        { "c4080", "DEEP SEA HOUND",                      6 },
        { "c4021", "ENLARGED HEAD",                      15 },
        { "c4022", "ENLARGED HEAD",                       4 },
        { "c4020", "ENLARGED HEAD PATIENT",              41 },
        { "c4120", "ENLARGED HEAD PATIENT",               2 },
        { "c2000", "EXECUTIONER",                        18 },
        { "c2710", "FATHER GASCOINGE",                    3 },
        { "c4040", "FISHWITCH",                          50 },
        { "c2530", "FLUORESCENT FLOWER",                  2 },
        { "c2632", "FOREST HUNTSMAN (TRANSFORMED)",      66 },
        { "c2110", "GARDEN OF EYES",                     16 },
        { "c2400", "GIANT LOST CHILD",                   13 },
        { "c1250", "GREATER VIPER PIT",                  12 },
        { "c2190", "HATEFUL MAGGOT",                     61 },
        { "c2610", "HEMWICK GRAVE WOMAN",                46 },
        { "c1140", "HUNTING DOG",                        14 },
        { "c2630", "HUNTSMAN (TRANSFORMED)",            283 },
        { "c1130", "OEDON CHAPEL DWELLER",                2 },  // name is OURS, not Characters.json: spec 032 D6 - see NAME_OVERRIDES
        { "c2540", "LARGE CRAWLER",                      20 },
        { "c2600", "LARGE HUNTSMAN",                     48 },
        { "c2631", "LARGE HUNTSMAN (TRANSFORMED)",        8 },
        { "c4110", "LARGE NIGHTMARE HUNTSMAN",           15 },
        { "c4050", "LIGHTNING SUMMONER",                 10 },
        { "c4051", "LIGHTNING SUMMONER",                  1 },
        { "c2050", "MAD ONE",                             9 },
        { "c1270", "MANEATER BOAR",                      13 },
        { "c1271", "MANEATER BOAR (AFFLICTED)",           3 },
        { "c2321", "MATYR LOGARIUS (SWORD)",              1 },
        { "c5160", "MENSIS BRAIN (DROPPED)",              1 },
        { "c2250", "MERGO'S ATTENDANT",                  18 },
        { "c2260", "MERGO'S CHIEF ATTENDANT",             3 },
        { "c1300", "NIGHTMARE APOSTLE",                   1 },
        { "c1111", "NIGHTMARE APOSTLE (PATCHES BODY)",   10 },
        { "c1110", "NIGHTMARE APOSTLE (PATCHES FACE)",    7 },
        { "c1400", "NIGHTMARE APOSTLE (ROM FACE)",       60 },
        { "c4010", "NIGHTMARE EXECUTIONER",               3 },
        { "c4000", "NIGHTMARE HUNTSMAN",                 14 },
        { "c4070", "ORPHAN OF KOS (SHELL)",              39 },
        { "c1100", "RAT",                                57 },
        { "c1120", "ROTTED CORPSE",                      63 },
        { "c2120", "SHADOW OF YHARNAM",                   7 },
        { "c2121", "SHADOW OF YHARNAM (SNAKE)",           8 },
        { "c1240", "SHAGGY HUNTING DOG",                 96 },
        { "c1241", "SHAGGY HUNTING DOG (CROW FACE)",      4 },
        { "c4060", "SHARK-GIANT",                         4 },
        { "c2150", "SILVER LADY",                        46 },
        { "c2040", "SKELETAL PUPPET",                    18 },
        { "c1001", "SKELETON-MEAT WOLF BEAST",           10 },
        { "c2740", "SLIME SCHOLAR",                      58 },
        { "c2500", "SMALL CELESTIAL EMISSARY",           50 },
        { "c4090", "SNAIL WOMAN",                         2 },
        { "c5033", "SNAKE",                               6 },
        { "c2020", "SNATCHER",                           22 },
        { "c2170", "VERMIN HOST",                        22 },
        { "c1260", "VIPER PIT HATCHLING",                88 },
        { "c2620", "WHEELCHAIR HUNTSMAN (GATLING GUN)",  25 },
        { "c2560", "WINTER LANTERN",                     10 },
        { "c2100", "WITCH OF HEMWICK",                    2 },
        { "c1000", "WOLF BEAST",                         31 },
    }};
    return kTable;
}

const int kEnemySkipModelCount = 85;

} // namespace bbr
