// EnemyPoolTable.h - GENERATED by tools/gen_pool_table.py enemy.
// Do not edit by hand; regenerate and re-run the matching verifier.
//
// Every model that can appear in the ENEMY randomizer's candidate pool,
// which is NOT the same as every enemy model in the game - placements on
// the exclusion list, with no think/npc param, or filtered by one of the
// two special cases in EnemyRandomizer.cpp never contribute.
//
// ORDER IS LOAD-BEARING: RandomizerDefaults stores the picker's selection
// as one character per row, positionally. Sorted by display name, then by
// model id to break ties - see the generator's header comment.
//
// Names are from tools/data/Characters.json (Smithbox, MIT) and are the
// community's labels, not From Software's - treated the same way every
// other name in this project is: useful, not authoritative.
//
// `poolEntries` is how many distinct stat/AI variants that model
// contributes, i.e. its relative draw weight. Unused by the app today;
// baked because it is free here and docs/deferred-ideas.md §2 needs it.
#pragma once

#include <array>

#include "ModelPoolSelection.h"

namespace bbr {

// Kept as a function-local static for the same reason as
// EnemyExclusionList(): header-only, no translation-unit duplication.
inline const std::array<ModelPoolEntry, 82>& EnemyPoolTable() {
    static const std::array<ModelPoolEntry, 82> kTable = {{
        { "c2180", "ABHORRENT BEAST",                     6 },
        { "c5040", "ABHORRENT BEAST",                     2 },
        { "c1091", "BEAST PATIENT",                       1 },
        { "c7500", "BEAST POSSESSED SOUL",                1 },
        { "c4100", "BLOOD DOBERMANN",                     1 },
        { "c2090", "BLOOD STARVED BEAST",                 1 },
        { "c2130", "BLOODLICKER",                         3 },
        { "c4130", "BLOODLICKER",                         1 },
        { "c1060", "BRAINSUCKER",                         5 },
        { "c2640", "BRICK TROLL",                        11 },
        { "c1220", "CAINHURST GARGOYLE",                  2 },
        { "c2330", "CAINHURST SERVANT",                   5 },
        { "c1170", "CARRION CROW",                       12 },
        { "c1171", "CARRION CROW (DOG FACE)",             1 },
        { "c2520", "CELESTIAL LARVAE",                    2 },
        { "c2521", "CELESTIAL LARVAE",                    1 },
        { "c2730", "CHAPEL GIANT",                        7 },
        { "c1050", "CHIME MAIDEN",                        4 },
        { "c1051", "CHIME MAIDEN (LIGHT)",               12 },
        { "c2700", "CHURCH SERVANT",                     13 },
        { "c1090", "CLOAKED BEAST PATIENT",               4 },
        { "c4140", "CLOAKED BEAST PATIENT",               2 },
        { "c1290", "CLOAKED BEAST PATIENT (FEMALE)",      2 },
        { "c3100", "CRAMPED CASKET",                      2 },
        { "c2550", "CRAWLER",                             2 },
        { "c4080", "DEEP SEA HOUND",                      1 },
        { "c4021", "ENLARGED HEAD",                       1 },
        { "c4022", "ENLARGED HEAD",                       1 },
        { "c4020", "ENLARGED HEAD PATIENT",              13 },
        { "c4120", "ENLARGED HEAD PATIENT",               2 },
        { "c2000", "EXECUTIONER",                         4 },
        { "c2710", "FATHER GASCOINGE",                    1 },
        { "c4040", "FISHWITCH",                           8 },
        { "c2530", "FLUORESCENT FLOWER",                  1 },
        { "c2632", "FOREST HUNTSMAN (TRANSFORMED)",      11 },
        { "c2110", "GARDEN OF EYES",                      1 },
        { "c2400", "GIANT LOST CHILD",                    3 },
        { "c1250", "GREATER VIPER PIT",                   2 },
        { "c2190", "HATEFUL MAGGOT",                      3 },
        { "c2610", "HEMWICK GRAVE WOMAN",                10 },
        { "c1140", "HUNTING DOG",                         1 },
        { "c2630", "HUNTSMAN (TRANSFORMED)",             41 },
        { "c2540", "LARGE CRAWLER",                       2 },
        { "c2600", "LARGE HUNTSMAN",                      7 },
        { "c2631", "LARGE HUNTSMAN (TRANSFORMED)",        2 },
        { "c4110", "LARGE NIGHTMARE HUNTSMAN",            5 },
        { "c4050", "LIGHTNING SUMMONER",                  2 },
        { "c4051", "LIGHTNING SUMMONER",                  1 },
        { "c2050", "MAD ONE",                             2 },
        { "c1270", "MANEATER BOAR",                       3 },
        { "c1271", "MANEATER BOAR (AFFLICTED)",           1 },
        { "c2321", "MATYR LOGARIUS (SWORD)",              1 },
        { "c5160", "MENSIS BRAIN (DROPPED)",              1 },
        { "c2250", "MERGO'S ATTENDANT",                   3 },
        { "c2260", "MERGO'S CHIEF ATTENDANT",             1 },
        { "c1300", "NIGHTMARE APOSTLE",                   1 },
        { "c1111", "NIGHTMARE APOSTLE (PATCHES BODY)",    1 },
        { "c1110", "NIGHTMARE APOSTLE (PATCHES FACE)",    1 },
        { "c1400", "NIGHTMARE APOSTLE (ROM FACE)",        1 },
        { "c4010", "NIGHTMARE EXECUTIONER",               3 },
        { "c4000", "NIGHTMARE HUNTSMAN",                  8 },
        { "c4070", "ORPHAN OF KOS (SHELL)",               3 },
        { "c1100", "RAT",                                 4 },
        { "c1120", "ROTTED CORPSE",                       5 },
        { "c2120", "SHADOW OF YHARNAM",                   3 },
        { "c1240", "SHAGGY HUNTING DOG",                  9 },
        { "c1241", "SHAGGY HUNTING DOG (CROW FACE)",      1 },
        { "c4060", "SHARK-GIANT",                         4 },
        { "c2150", "SILVER LADY",                         2 },
        { "c2040", "SKELETAL PUPPET",                     1 },
        { "c1001", "SKELETON-MEAT WOLF BEAST",            1 },
        { "c2740", "SLIME SCHOLAR",                       6 },
        { "c2500", "SMALL CELESTIAL EMISSARY",            9 },
        { "c4090", "SNAIL WOMAN",                         1 },
        { "c5033", "SNAKE",                               1 },
        { "c2020", "SNATCHER",                            2 },
        { "c2170", "VERMIN HOST",                         4 },
        { "c1260", "VIPER PIT HATCHLING",                 3 },
        { "c2620", "WHEELCHAIR HUNTSMAN (GATLING GUN)",  12 },
        { "c2560", "WINTER LANTERN",                      4 },
        { "c2100", "WITCH OF HEMWICK",                    1 },
        { "c1000", "WOLF BEAST",                          4 },
    }};
    return kTable;
}

const int kEnemyPoolModelCount = 82;

} // namespace bbr
