// LeftHandWeaponTable.h - GENERATED by tools/gen_left_hand_table.py.
// Do not edit by hand; regenerate and re-run left_hand_weapons_verify.py.
//
// Every left-hand weapon a player can be granted at character
// creation - feature 038, START WITH A LEFT-HAND WEAPON. Feature 037's
// table for the other hand: 11 firearms plus the Loch Shield, the
// Hunter's Torch and the Fist of Gratia.
//
// The set is DERIVED, not listed: a tier-0 EquipParamWeapon row with the
// leftHandEquipable bit set (byte 256 bit 1), named by the game's own
// text, AND obtainable in vanilla from a shop or an item lot. Trick
// weapons are right-hand items and are absent; so are Bare Fists, the
// two unnamed rows, and the Wooden Shield and the Torch, which the
// game names but no shop and no item lot can give a player.
//
// UNLIKE FEATURE 037'S TABLE THIS ONE IS FLAT. No left-hand weapon has
// an Uncanny or a Lost form, so there is no version dimension and each
// weapon is exactly one row. The generator asserts that rather than
// assuming it.
//
// ORDER IS LOAD-BEARING: RandomizerDefaults stores the picker's selection
// as one character per row, positionally. Sorted by name, by the same
// frozen rule TrickWeaponTable.h uses. A regenerated table in a
// different order silently remaps a saved selection onto the wrong
// weapon.
//
// `model` holds the weapon id in DECIMAL, as a string, because the picker
// keys and logs on that field; the engine converts it with strtol. There
// is deliberately no second array of ids to fall out of step with this.
// `poolEntries` is 1 for every row: each row is exactly one weapon.
//
// Names are FROM THE GAME'S OWN TEXT, uppercased, read at each exact id -
// never composed.
#pragma once

#include <array>

#include "ModelPoolSelection.h"

namespace bbr {

// Kept as a function-local static for the same reason as the pool tables:
// header-only, no translation-unit duplication.
inline const std::array<ModelPoolEntry, 14>& LeftHandWeaponTable() {
    static const std::array<ModelPoolEntry, 14> kTable = {{
        { "15000000",  "CANNON",             1 },
        { "35000000",  "CHURCH CANNON",      1 },
        { "14100000",  "EVELYN",             1 },
        { "34000000",  "FIST OF GRATIA",     1 },
        { "18100000",  "FLAMESPRAYER",       1 },
        { "33000000",  "GATLING GUN",        1 },
        { "6000000",   "HUNTER BLUNDERBUSS", 1 },
        { "14000000",  "HUNTER PISTOL",      1 },
        { "20000000",  "HUNTER'S TORCH",     1 },
        { "19100000",  "LOCH SHIELD",        1 },
        { "6100000",   "LUDWIG'S RIFLE",     1 },
        { "36000000",  "PIERCING RIFLE",     1 },
        { "14200000",  "REPEATING PISTOL",   1 },
        { "18000000",  "ROSMARINUS",         1 },
    }};
    return kTable;
}

const int kLeftHandWeaponCount = 14;

} // namespace bbr
