// TrickWeaponTable.h - GENERATED by tools/gen_weapon_table.py.
// Do not edit by hand; regenerate and re-run trick_weapons_verify.py.
//
// Every right-hand trick-weapon VERSION a player can be granted at
// character creation - feature 037, START WITH A TRICK WEAPON. The 26
// trick weapons, each three times: the plain weapon, its Uncanny version
// (version 1) and its Lost version (version 2).
//
// The set is DERIVED, not listed: a tier-0 EquipParamWeapon row with the
// rightHandEquipable bit set (byte 256 bit 0), named by the game's own
// text, and obtainable in vanilla from a shop or an item lot. Firearms,
// shields and torches are left-hand items and are absent; so are Bare
// Fists and the seven unnamed, unobtainable right-hand rows. See the
// generator's header comment for why two independent tests, not one.
//
// ORDER IS LOAD-BEARING: RandomizerDefaults stores the picker's selection
// as one character per row, positionally. Sorted by the weapon's base
// (version-0) name, then version 0/1/2, so a weapon's three rows are
// adjacent. A regenerated table in a different order silently remaps a
// saved selection onto the wrong VERSION of a weapon.
//
// `model` holds the weapon id in DECIMAL, as a string, because the picker
// keys and logs on that field; the engine converts it with strtol. There
// is deliberately no second array of ids to fall out of step with this.
// `poolEntries` is 1 for every row: each row is exactly one weapon.
//
// Names are FROM THE GAME'S OWN TEXT, uppercased, read at each exact id -
// never composed from a prefix. Four of the 26 are spelled irregularly.
#pragma once

#include <array>

#include "ModelPoolSelection.h"

namespace bbr {

// Kept as a function-local static for the same reason as the pool tables:
// header-only, no translation-unit duplication.
inline const std::array<ModelPoolEntry, 78>& TrickWeaponTable() {
    static const std::array<ModelPoolEntry, 78> kTable = {{
        { "25000000",  "AMYGDALAN ARM",                1 },
        { "25010000",  "UNCANNY AMYGDALAN ARM",        1 },
        { "25020000",  "LOST AMYGDALAN ARM",           1 },
        { "9000000",   "BEAST CLAW",                   1 },
        { "9010000",   "UNCANNY BEAST CLAW",           1 },
        { "9020000",   "LOST BEAST CLAW",              1 },
        { "24000000",  "BEAST CUTTER",                 1 },
        { "24010000",  "UNCANNY BEAST CUTTER",         1 },
        { "24020000",  "LOST BEAST CUTTER",            1 },
        { "23000000",  "BEASTHUNTER SAIF",             1 },
        { "23010000",  "UNCANNY BEASTHUNTER SAIF",     1 },
        { "23020000",  "LOST BEASTHUNTER SAIF",        1 },
        { "4000000",   "BLADE OF MERCY",               1 },
        { "4010000",   "UNCANNY BLADE OF MERCY",       1 },
        { "4020000",   "LOST BLADE OF MERCY",          1 },
        { "29000000",  "BLOODLETTER",                  1 },
        { "29010000",  "UNCANNY BLOODLETTER",          1 },
        { "29020000",  "LOST BLOODLETTER",             1 },
        { "28000000",  "BOOM HAMMER",                  1 },
        { "28010000",  "UNCANNY BOOM HAMMER",          1 },
        { "28020000",  "LOST BOOM HAMMER",             1 },
        { "5100000",   "BURIAL BLADE",                 1 },
        { "5110000",   "UNCANNY BURIAL BLADE",         1 },
        { "5120000",   "LOST BURIAL BLADE",            1 },
        { "2000000",   "CHIKAGE",                      1 },
        { "2010000",   "UNCANNY CHIKAGE",              1 },
        { "2020000",   "LOST CHIKAGE",                 1 },
        { "30000000",  "CHURCH PICK",                  1 },
        { "30010000",  "UNCANNY CHURCH PICK",          1 },
        { "30020000",  "LOST CHURCH PICK",             1 },
        { "26000000",  "HOLY MOONLIGHT SWORD",         1 },
        { "26010000",  "UNCANNY HOLY MOONLIGHT SWORD", 1 },
        { "26020000",  "LOST HOLY MOONLIGHT SWORD",    1 },
        { "5000000",   "HUNTER AXE",                   1 },
        { "5010000",   "UNCANNY HUNTER AXE",           1 },
        { "5020000",   "LOST HUNTER AXE",              1 },
        { "8000000",   "KIRKHAMMER",                   1 },
        { "8010000",   "UNCANNY KIRKHAMMER",           1 },
        { "8020000",   "LOST KIRKHAMMER",              1 },
        { "38000000",  "KOS PARASITE",                 1 },
        { "38010000",  "UNCANNY PARASITE",             1 },
        { "38020000",  "LOST PARASITE",                1 },
        { "12000000",  "LOGARIUS' WHEEL",              1 },
        { "12010000",  "LOGARIUS' UNCANNY WHEEL",      1 },
        { "12020000",  "LOGARIUS' LOST WHEEL",         1 },
        { "8100000",   "LUDWIG'S HOLY BLADE",          1 },
        { "8110000",   "LUDWIG'S UNCANNY HOLY BLADE",  1 },
        { "8120000",   "LUDWIG'S LOST HOLY BLADE",     1 },
        { "27000000",  "RAKUYO",                       1 },
        { "27010000",  "UNCANNY RAKUYO",               1 },
        { "27020000",  "LOST RAKUYO",                  1 },
        { "10100000",  "REITERPALLASCH",               1 },
        { "10110000",  "UNCANNY REITERPALLASCH",       1 },
        { "10120000",  "LOST REITERPALLASCH",          1 },
        { "10000000",  "RIFLE SPEAR",                  1 },
        { "10010000",  "UNCANNY RIFLE SPEAR",          1 },
        { "10020000",  "LOST RIFLE SPEAR",             1 },
        { "7000000",   "SAW CLEAVER",                  1 },
        { "7010000",   "UNCANNY SAW CLEAVER",          1 },
        { "7020000",   "LOST SAW CLEAVER",             1 },
        { "7100000",   "SAW SPEAR",                    1 },
        { "7110000",   "UNCANNY SAW SPEAR",            1 },
        { "7120000",   "LOST SAW SPEAR",               1 },
        { "32000000",  "SIMON'S BOWBLADE",             1 },
        { "32010000",  "UNCANNY BOWBLADE",             1 },
        { "32020000",  "LOST BOWBLADE",                1 },
        { "11000000",  "STAKE DRIVER",                 1 },
        { "11010000",  "UNCANNY STAKE DRIVER",         1 },
        { "11020000",  "LOST STAKE DRIVER",            1 },
        { "22000000",  "THREADED CANE",                1 },
        { "22010000",  "UNCANNY THREADED CANE",        1 },
        { "22020000",  "LOST THREADED CANE",           1 },
        { "13000000",  "TONITRUS",                     1 },
        { "13010000",  "UNCANNY TONITRUS",             1 },
        { "13020000",  "LOST TONITRUS",                1 },
        { "31000000",  "WHIRLIGIG SAW",                1 },
        { "31010000",  "UNCANNY WHIRLIGIG SAW",        1 },
        { "31020000",  "LOST WHIRLIGIG SAW",           1 },
    }};
    return kTable;
}

const int kTrickWeaponCount = 78;

} // namespace bbr
